apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: namespace-frontend-1
  labels:
    app: a15-redis-avail
  name: redis-master
spec:
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-master
  type: ClusterIP
status:
  loadBalancer: {}
