apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: namespace-frontend-1
  labels:
    app: frontend-cip
  name: frontend-cip
spec:
  ports:
  - name: "80"
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
status:
  loadBalancer: {}
