apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-master
  namespace: namespace-frontend-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-master
    spec:
      containers:
      - image: redis:6.0.5
        name: redis-leader
        ports:
        - containerPort: 6379
        env:
        - name: thisis
          value: redis-master
