version: "3"
services:
  myimage:
    image: gcr.io/google_samples/gb-frontend:v5
    networks:
      - frontend
      - redis
    ports:
      - 80:80
    links:
      - redis-leader
      - redis-follower
    volumes:
      - ./index.html:/var/www/html/index.html
  redis-leader:
    image: redis:6.0.5
    networks: 
      - redis
    volumes:
      - ./redis-persistent/:/data
  redis-follower:
    image: gcr.io/google_samples/gb-redis-follower:v2
    networks:
      - redis
networks:
 redis:
 frontend:
