apiVersion: v1
data:
  var1: valuesome
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <title>From config map</title>
      </head>
      <body>
      
        <h1>Loaded from config map!</h1>
      
      </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: confmap1
  namespace: namespace-frontend-1
