apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: namespace-redis-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
        gb-component: redis
    spec:
      containers:
      - image: redis:6.0.5
        name: redis-leader
        ports:
        - containerPort: 80
        env:
        - name: thisis
          value: redis-master
      serviceAccountName: redis-svcacc
